# Generated by Django 4.0.3 on 2023-06-25 20:26

from django.db import migrations, models
import java_wallet.fields


class Migration(migrations.Migration):

    dependencies = [
        ('java_wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndirecIncoming',
            fields=[
                ('db_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_id', java_wallet.fields.PositiveBigIntegerField()),
                ('transaction_id', java_wallet.fields.PositiveBigIntegerField()),
                ('height', models.IntegerField()),
                ('amount', java_wallet.fields.PositiveBigIntegerField(null=True)),
                ('quantity', java_wallet.fields.PositiveBigIntegerField(null=True)),
            ],
            options={
                'db_table': 'indirect_incoming',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='forged_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='unconfirmed_balance',
        ),
        migrations.RemoveField(
            model_name='block',
            name='version',
        ),
        migrations.RemoveField(
            model_name='version',
            name='id',
        ),
        migrations.AddField(
            model_name='alias',
            name='tld',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='mintable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='at',
            name='ap_code_hash_id',
            field=java_wallet.fields.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='total_fee_burnt',
            field=java_wallet.fields.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='total_fee_cash_back',
            field=java_wallet.fields.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_back_id',
            field=java_wallet.fields.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='at',
            name='ap_code',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='atstate',
            name='state',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='next_update',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('db_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', java_wallet.fields.PositiveBigIntegerField()),
                ('balance', java_wallet.fields.PositiveBigIntegerField()),
                ('unconfirmed_balance', java_wallet.fields.PositiveBigIntegerField()),
                ('forged_balance', java_wallet.fields.PositiveBigIntegerField()),
                ('height', models.IntegerField()),
                ('latest', models.IntegerField()),
            ],
            options={
                'db_table': 'account_balance',
                'managed': True,
                'unique_together': {('id', 'height')},
            },
        ),
    ]
