# Generated by Django 4.0.3 on 2023-06-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('java_wallet', '0002_indirecincoming_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndirecIncoming',
            new_name='IndirectIncoming',
        ),
    ]
