# Generated by Django 4.0.3 on 2023-06-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiOut',
        ),
        migrations.AlterField(
            model_name='peermonitor',
            name='reward_state',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
    ]
